services:
  db:
    image: postgres:13
    env_file: "./.env.docker"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: 
      context: ./  
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: "./.env.docker"

volumes:
  pgdata:


  