"""changed email for user_id in Openings table

Revision ID: ad7ea5aa4f1d
Revises: 56bfeb76cacb
Create Date: 2024-09-18 16:09:39.959846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad7ea5aa4f1d'
down_revision: Union[str, None] = '56bfeb76cacb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('openings', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index('ix_openings_email', table_name='openings')
    op.create_index(op.f('ix_openings_user_id'), 'openings', ['user_id'], unique=False)
    op.drop_constraint('openings_email_fkey', 'openings', type_='foreignkey')
    op.create_foreign_key(None, 'openings', 'users', ['user_id'], ['id'])
    op.drop_column('openings', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('openings', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'openings', type_='foreignkey')
    op.create_foreign_key('openings_email_fkey', 'openings', 'users', ['email'], ['email'])
    op.drop_index(op.f('ix_openings_user_id'), table_name='openings')
    op.create_index('ix_openings_email', 'openings', ['email'], unique=False)
    op.drop_column('openings', 'user_id')
    # ### end Alembic commands ###
